name: CI / CD - Ejemplo

on:
 push:
  tags:
    - 'v*'
    
jobs:
 build: 
  runs-on: ubuntu-latest
  
  strategy:
    matrix:
      node-version: [16.x]
      
  steps:
   - uses: actions/checkout@v2
   
   - name: build backend
     working-directory: backend
     run: |
       npm install
       npm run start
