name: CI / CD - Ejemplo

on:
 push:
  tags:
    - 'v*'
    
jobs:
 build: 
  runs-on: ubuntu-latest
  
  strategy:
    matrix:
      node-version: [16.x]
      
  steps:
   - uses: actions/checkout@v2
   
   - name: build backend
     working-directory: backend
     run: |
       npm install
       
   - name: build docker backend image
     working-directory: backend
     run: |
      docker build -t developermartinfernandez/backend-twitch:$(echo ${GITHUB_REF:10}) .
    
   - name: Login de docker hub
     uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
     with: 
       registry: docker.io
       username: developermartinfernandez
       password: ${{ secrets.TOKEN_DE_DOCKER_HUB }}
       
   - name: Publish Image
     run: |
      docker image push developermartinfernandez/backend-twitch:$(echo ${GITHUB_REF:10})
     
   
